// <auto-generated />
namespace Entity_Framework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class order_and_order_item : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(order_and_order_item));
        
        string IMigrationMetadata.Id
        {
            get { return "201903071351507_order_and_order_item"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
